name: Hops
modelClass: Eliseontwerpt\Brouwerbouwer\Models\Hops
form: $/eliseontwerpt/brouwerbouwer/models/listofhops/fields.yaml
defaultRedirect: eliseontwerpt/brouwerbouwer/listofhops
create:
    redirect: 'eliseontwerpt/brouwerbouwer/listofhops/update/:id'
    redirectClose: eliseontwerpt/brouwerbouwer/listofhops
update:
    redirect: eliseontwerpt/brouwerbouwer/listofhops
    redirectClose: eliseontwerpt/brouwerbouwer/listofhops
