name: Hops
modelClass: Eliseontwerpt\Brouwerbouwer\Models\Hops
form: $/eliseontwerpt/brouwerbouwer/models/hops/fields.yaml
defaultRedirect: eliseontwerpt/brouwerbouwer/hops
create:
    redirect: 'eliseontwerpt/brouwerbouwer/hops/update/:id'
    redirectClose: eliseontwerpt/brouwerbouwer/hops
update:
    redirect: eliseontwerpt/brouwerbouwer/hops
    redirectClose: eliseontwerpt/brouwerbouwer/hops
