title: Recipes
modelClass: Eliseontwerpt\Brouwerbouwer\Models\Recipes
list: $/eliseontwerpt/brouwerbouwer/models/recipes/columns.yaml
recordUrl: 'eliseontwerpt/brouwerbouwer/recipes/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
