name: Recipes
modelClass: Eliseontwerpt\Brouwerbouwer\Models\Recipes
form: $/eliseontwerpt/brouwerbouwer/models/recipes/fields.yaml
defaultRedirect: eliseontwerpt/brouwerbouwer/recipes
create:
    redirect: 'eliseontwerpt/brouwerbouwer/recipes/update/:id'
    redirectClose: eliseontwerpt/brouwerbouwer/recipes
update:
    redirect: 'eliseontwerpt/brouwerbouwer/recipes/update/:id'
    redirectClose: eliseontwerpt/brouwerbouwer/recipes

