# ===================================
#  Relation Behavior Config
# ===================================

malts:
    label: 'eliseontwerpt.brouwerbouwer::lang.malts.name'
    manage:
        form: $/eliseontwerpt/brouwerbouwer/models/malts/fields.yaml
        list:  $/eliseontwerpt/brouwerbouwer/models/malts/columns.yaml

    view:
        list: $/eliseontwerpt/brouwerbouwer/models/malts/columns.yaml
        toolbarButtons: create|delete

hops:
    label: 'eliseontwerpt.brouwerbouwer::lang.listofhops.name'
    manage:
        form: $/eliseontwerpt/brouwerbouwer/models/listofhops/fields.yaml
        list:  $/eliseontwerpt/brouwerbouwer/models/listofhops/columns.yaml

    view:
        list: $/eliseontwerpt/brouwerbouwer/models/listofhops/columns.yaml
        toolbarButtons: create|delete

mashscheme:
    label: 'eliseontwerpt.brouwerbouwer::lang.mashscheme.name'
    manage:
        form: $/eliseontwerpt/brouwerbouwer/models/mashscheme/fields.yaml
        list:  $/eliseontwerpt/brouwerbouwer/models/mashscheme/columns.yaml

    view:
        list: $/eliseontwerpt/brouwerbouwer/models/mashscheme/columns.yaml
        toolbarButtons: create|delete
