title: Malts
modelClass: Eliseontwerpt\Brouwerbouwer\Models\Malts
list: $/eliseontwerpt/brouwerbouwer/models/malts/columns.yaml
recordUrl: 'eliseontwerpt/brouwerbouwer/malts/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
