list: $/eliseontwerpt/brouwerbouwer/models/brewday/columns.yaml
modelClass: Eliseontwerpt\Brouwerbouwer\Models\Brewday
title: Brewday
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'eliseontwerpt/brouwerbouwer/brewday/update/:id'
