name: Brewday
modelClass: Eliseontwerpt\Brouwerbouwer\Models\Brewday
form: $/eliseontwerpt/brouwerbouwer/models/brewday/fields.yaml
defaultRedirect: hjp/brouwerbouwer/brewday
create:
    redirect: 'eliseontwerpt/brouwerbouwer/brewday/update/:id'
    redirectClose: eliseontwerpt/brouwerbouwer/brewday
update:
    redirect: eliseontwerpt/brouwerbouwer/brewday
    redirectClose: eliseontwerpt/brouwerbouwer/brewday
