# ===================================
#  Relation Behavior Config
# ===================================

recipes:
    label: 'eliseontwerpt.brouwerbouwer::lang.recipes.name'
    manage:
        form: $/eliseontwerpt/brouwerbouwer/models/recipes/fields.yaml
        list:  $/eliseontwerpt/brouwerbouwer/models/recipes/columns.yaml
        
    view:
        list: $/eliseontwerpt/brouwerbouwer/models/recipes/columns.yaml
        toolbarButtons: create|delete