title: ListOfHops
modelClass: EliseOntwerpt\Brouwerbouwer\Models\ListOfHops
list: $/eliseontwerpt/brouwerbouwer/models/listofhops/columns.yaml
recordUrl: 'eliseontwerpt/brouwerbouwer/listofhops/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
