name: BjcpValues
modelClass: Eliseontwerpt\Brouwerbouwer\Models\BjcpValues
form: $/eliseontwerpt/brouwerbouwer/models/bjcpvalues/fields.yaml
defaultRedirect: eliseontwerpt/brouwerbouwer/bjcpvalues
create:
    redirect: 'eliseontwerpt/brouwerbouwer/bjcpvalues/update/:id'
    redirectClose: eliseontwerpt/brouwerbouwer/bjcpvalues
update:
    redirect: eliseontwerpt/brouwerbouwer/bjcpvalues
    redirectClose: eliseontwerpt/brouwerbouwer/bjcpvalues
preview: {  }
