title: BjcpCategoriesGuide
modelClass: EliseOntwerpt\Brouwerbouwer\Models\BjcpCategoriesGuide
list: $/eliseontwerpt/brouwerbouwer/models/bjcpcategoriesguide/columns.yaml
recordUrl: 'eliseontwerpt/brouwerbouwer/bjcpcategoriesguide/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
