title: WaterProfiles
modelClass: EliseOntwerpt\Brouwerbouwer\Models\WaterProfiles
list: $/eliseontwerpt/brouwerbouwer/models/waterprofiles/columns.yaml
recordUrl: 'eliseontwerpt/brouwerbouwer/waterprofiles/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: '10'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
