name: WaterProfiles
modelClass: EliseOntwerpt\Brouwerbouwer\Models\WaterProfiles
form: $/eliseontwerpt/brouwerbouwer/models/waterprofiles/fields.yaml
defaultRedirect: eliseontwerpt/brouwerbouwer/waterprofiles
create:
    redirect: 'eliseontwerpt/brouwerbouwer/waterprofiles/update/:id'
    redirectClose: eliseontwerpt/brouwerbouwer/waterprofiles
update:
    redirect: eliseontwerpt/brouwerbouwer/waterprofiles
    redirectClose: eliseontwerpt/brouwerbouwer/waterprofiles
