name: ListOfMalts
modelClass: Eliseontwerpt\Brouwerbouwer\Models\ListOfMalts
form: $/eliseontwerpt/brouwerbouwer/models/listofmalts/fields.yaml
defaultRedirect: eliseontwerpt/brouwerbouwer/listofmalts
create:
    redirect: 'eliseontwerpt/brouwerbouwer/listofmalts/update/:id'
    redirectClose: eliseontwerpt/brouwerbouwer/listofmalts
update:
    redirect: eliseontwerpt/brouwerbouwer/listofmalts
    redirectClose: eliseontwerpt/brouwerbouwer/listofmalts
preview: {  }
