name: Gear
modelClass: Eliseontwerpt\Brouwerbouwer\Models\Gear
form: $/eliseontwerpt/brouwerbouwer/models/gear/fields.yaml
defaultRedirect: eliseontwerpt/brouwerbouwer/gear
create:
    redirect: 'eliseontwerpt/brouwerbouwer/gear/update/:id'
    redirectClose: eliseontwerpt/brouwerbouwer/gear
update:
    redirect: eliseontwerpt/brouwerbouwer/gear
    redirectClose: eliseontwerpt/brouwerbouwer/gear
preview: {  }
