name: MashScheme
form: $/eliseontwerpt/brouwerbouwer/models/mashscheme/fields.yaml
modelClass: Eliseontwerpt\Brouwerbouwer\Models\MashScheme
defaultRedirect: eliseontwerpt/brouwerbouwer/mashscheme
create:
    redirect: 'eliseontwerpt/brouwerbouwer/mashscheme/update/:id'
    redirectClose: eliseontwerpt/brouwerbouwer/mashscheme
update:
    redirect: eliseontwerpt/brouwerbouwer/mashscheme
    redirectClose: eliseontwerpt/brouwerbouwer/mashscheme
