list: $/eliseontwerpt/brouwerbouwer/models/mashscheme/columns.yaml
modelClass: eliseontwerpt\Brouwerbouwer\Models\MashScheme
title: MashScheme
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'eliseontwerpt/brouwerbouwer/mashscheme/update/:id'
