name: BjcpStyleGuide
modelClass: Eliseontwerpt\Brouwerbouwer\Models\BjcpStyleGuide
form: $/eliseontwerpt/brouwerbouwer/models/bjcpstyleguide/fields.yaml
defaultRedirect: eliseontwerpt/brouwerbouwer/bjcpstyleguide
create:
    redirect: 'eliseontwerpt/brouwerbouwer/bjcpstyleguide/update/:id'
    redirectClose: eliseontwerpt/brouwerbouwer/bjcpstyleguide
update:
    redirect: eliseontwerpt/brouwerbouwer/bjcpstyleguide
    redirectClose: eliseontwerpt/brouwerbouwer/bjcpstyleguide
preview: {  }
