list: $/eliseontwerpt/brouwerbouwer/models/bjcpstyleguide/columns.yaml
modelClass: Eliseontwerpt\Brouwerbouwer\Models\BjcpStyleGuide
title: BjcpStyleGuide
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'eliseontwerpt/brouwerbouwer/bjcpstyleguide/update/:id'
